[helpers]
color_rgb = ".dotter/helpers/color_rgb.rhai"

[default]
depends = []

[default.files]
"README.md" = ""

[default.variables]

[shell.files]
# Optional local variables: email+git_username
tmux = "~/.tmux.conf"
scripts = "~/.scripts"
dir_colors = "~/.dir_colors"
git_prompt = "~/.git_prompt"
bat = "~/.config/bat/config"
ripgrep = { type = "symbolic", target = "~/.ripgreprc", if = '(is_executable "rg")'}
"atuin.toml" = { type = "symbolic", target = "~/.config/atuin/config.toml", if = '(is_executable "atuin")'}

[shell.variables]
# Local variables: install, uninstall, update, autoremove, user_color
# defined for each OS in .dotter/include/<OS>.toml
install = "echo not defined"
uninstall = "echo not defined"
update = "echo not defined"
autoremove = "echo not defined"
user_color = "7"

[bash]
depends = ["shell"]

[cargo.files]
cargo = "~/.cargo/config"

[vim.files]
# Optional local variables: arm
nvim = "~/.config/nvim"

[graphics.variables.colors]
background = "222222"
background_alt = "444444"
background_bright = "666666"
text_muted = "666666"
text = "dedede"
text_bright = "ffffff"
accent = "bd2c40"

[graphics.variables.colors16]
background   = "151515"
foreground   = "d7d0c7"
cursor       = "d7d0c7"
# In terminal color index order
black        = "101010"
red          = "e84f4f"
green        = "b8d68c"
yellow       = "e1aa5d"
blue         = "7dc1cf"
purple       = "9b64fb"
cyan         = "6d878d"
light_gray   = "dddddd"
dark_gray    = "404040"
light_red    = "d23d3d"
light_green  = "a0cf5d"
light_yellow = "f39d21"
light_blue   = "4e9fb1"
light_purple = "8542ff"
light_cyan   = "42717b"
white        = "dddddd"

#[graphics.variables.font]
#regular = "Ubuntu"
#monospace = "Fira Code"
#size = 12