[helpers]
color_rgb = ".dotter/helpers/color_rgb.rhai"

[default]
depends = []

[default.files]
"README.md" = ""

[default.variables]

[shell.files]
# Optional local variables: email+git_username
tmux = "~/.tmux.conf"
scripts = "~/.scripts"
dir_colors = "~/.dir_colors"
git_prompt = "~/.git_prompt"
bat = "~/.config/bat/config"
ripgrep = { type = "symbolic", target = "~/.ripgreprc", if = '(is_executable "rg")'}
"atuin.toml" = { type = "symbolic", target = "~/.config/atuin/config.toml", if = '(is_executable "atuin")'}

[shell.variables]
# Local variables: install, uninstall, update, autoremove, user_color
# defined for each OS in .dotter/include/<OS>.toml
install = "echo not defined"
uninstall = "echo not defined"
update = "echo not defined"
autoremove = "echo not defined"
user_color = "7"

[bash]
depends = ["shell"]

[cargo.files]
cargo = "~/.cargo/config.toml"

[vim.files]
nvim = "~/.config/nvim"

[zsh]
depends = ["shell"]

[zsh.files]
zshenv = "~/.zshenv"
zshrc = "~/.zshrc"

[zsh.variables]

[i3.files]
i3 = "~/.config/i3/config"

[i3.variables]

[nuget.files]
nuget = "~/.nuget/NuGet/NuGet.Config"

[nuget.variables]

[pulse.files]
pulse = "~/.pulse/default.pa"

[pulse.variables]

[alacritty.files]
alacritty = "~/.config/alacritty"

[alacritty.variables]
